--- 
categories: 
  - 
    name: program
custom: 
  category: ~
desc: "长路漫漫 无心停留"
exclude: 
  - README.md
funny: 折腾
golang: golang
host: "http://afredlyj.github.io/"
markdown: kramdown
meta: 
  author: 
    disqus: your-disqus-short-name
    email: csulyj@gmail.com
    gcse: "018154889538965992626:ibsyratvihw"
    github: "https://github.com/afredlyj"
    gravatar: 7dfb3c6fe5d0c1f5121d7d6d311fa8ff
    name: Afred
  disqus: disqus.com/embed.js
  gapi: "http://www.google.com/jsapi"
  gravatar: "http://en.gravatar.com/avatar/"
name: "Afred's Blog"
permalink: "/posts/:title.html"
program: 编程之旅
pygments: true
safe: false
shell: shell脚本
title: 折腾

